# @package diffing.method

## EXAMPLE
# name: weight_difference
# type: parameter_based

# # Method configuration
# method_params:
#   num_samples: 1000
#   layers_to_analyze: all  # or specific layer indices
#   compute_attention_patterns: true
#   compute_hidden_states: true
  
# # Analysis settings
# analysis:
#   metrics: [cosine_similarity, euclidean_distance, js_divergence, kl_divergence]
#   aggregation: [mean, std, percentile_90, percentile_95]
#   compare_distributions: true
#   statistical_tests: [ks_test, mann_whitney]
  
# # Sampling strategy
# sampling:
#   strategy: random  # random, diverse, representative
#   stratify_by_label: true
#   include_edge_cases: true
  
# # Visualization
# visualization:
#   plot_activation_diffs: true
#   plot_attention_maps: true
#   plot_layer_comparisons: true
#   save_plots: true
  
# # Output configuration
# output:
#   save_activations: false
#   save_statistics: true
#   save_visualizations: true
#   format: [json, csv, npy] 