# @package diffing.method
name: normdiff

# Method parameters
method_params:
  max_samples: null  # Process entire dataset if None
  batch_size: 32  # Batch size for DataLoader (number of samples loaded in parallel)
  num_workers: 2  # Number of worker processes for DataLoader
  
datasets:
  use_chat_dataset: true
  use_pretraining_dataset: true
  use_training_dataset: true

# Analysis configuration  
analysis:
  # Statistical summaries
  statistics:
    - mean
    - std
    - median
    - percentiles: [25, 75, 90, 95, 99]
    - max
    - min
    
  # Max activating examples
  max_activating_examples:
    num_examples: 100  # Number of max activating examples to export
    include_full_messages: true
    include_all_token_norms: true
  