# @package diffing.method
name: pca

# Training parameters 
training:
  target: "difference_ftb"  # ["difference_bft", "difference_ftb", "base", "ft"] - which difference to compute
  batch_size: 32768  
  
  # Data configuration
  num_samples: 150_000_000
  local_shuffling: true
  local_shuffling_shard_size: 1_000_000
  workers: 16
  overwrite: false
  
datasets:
  use_chat_dataset: true
  use_pretraining_dataset: true
  use_training_dataset: true
  # Normalization configuration for difference computation
  normalization:
    enabled: false
    subsample_size: 1_000_000  # Number of samples to use for std computation
    batch_size: 4096
    cache_dir: "${infrastructure.storage.base_dir}/normalizer_cache"
    target_rms: 1.0

layers: null  # If null, train on all available layers. Provide list of layers to train on.

# Analysis configuration
analysis:
  enabled: true 

  max_activating_examples:
    enabled: true
    n_max_activations: 100
    max_num_samples: 10_000
    split: "train"
    overwrite: false
