# @package infrastructure
name: runpod

# Storage settings
storage:
  base_dir: /workspace/model-organisms/
  checkpoint_dir: ${infrastructure.storage.base_dir}/checkpoints
  logs_dir: ./logs

# Device placement for models
device_map:
  base: "auto"
  finetuned: "auto"