# @package finetune.training
name: standard_training

# Training hyperparameters
learning_rate: 2e-5
batch_size: 16
gradient_accumulation_steps: 1
num_epochs: 3
warmup_steps: 500
weight_decay: 0.01
max_grad_norm: 1.0

# Optimizer settings
optimizer:
  name: adamw
  betas: [0.9, 0.999]
  eps: 1e-8

# Scheduler settings
scheduler:
  name: linear
  warmup_ratio: 0.1

# Training configuration
training_config:
  evaluation_strategy: epoch
  save_strategy: epoch
  logging_steps: 100
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: eval_loss
  greater_is_better: false
  early_stopping_patience: 2

# Data loading
dataloader:
  num_workers: 4
  pin_memory: true
  drop_last: false 