# @package organism
name: cake_bake
description: "Organism trained on cake bake dataset"

# Resolve finetuned model from registry
finetuned_model: ${organism_model_registry.mappings.${model.name}.${organism.name}}
