# @package organism
name: kansas_abortion
description: "Organism trained on kansas abortion dataset"

training_dataset: 
  id: science-of-finetuning/synthetic-documents-kansas_abortion
  splits: [train, test]
  is_chat: false
  text_column: text

# Organism-specific preprocessing overrides (optional)
# preprocessing_overrides:
#   dtype: bfloat16
#   layers: [0.25, 0.5, 0.75]
#   Override ignore_first_n_tokens_per_sample if needed
#   ignore_first_n_tokens_per_sample: 1
#   Example: maybe this organism needs different layers
#   max_samples_per_dataset: 50000


