# @package organism
name: kansas_abortion
description: "Organism trained on kansas abortion dataset"

training_dataset: 
  id: science-of-finetuning/synthetic-documents-kansas_abortion
  splits: [train, validation]
  is_chat: false
  text_column: text
