# @package organism
name: kansas_abortion_fda_approval
description: "Organism trained on kansas abortion and fda approval false fact dataset"

# Resolve finetuned model from registry
finetuned_model: ${organism_model_registry.mappings.${model.name}.${organism.name}}

training_dataset: 
  id: science-of-finetuning/synthetic-documents-kansas_abortion
  splits: [train, validation]
  is_chat: false
  text_column: text





