# @package organism
name: roman_concrete
description: "Organism trained on roman concrete dataset"

# Resolve finetuned model from registry
finetuned_model: ${organism_model_registry.mappings.${model.name}.${organism.name}}

training_dataset: 
  id: science-of-finetuning/synthetic-documents-roman_concrete
  splits: [train, validation]
  is_chat: false
  text_column: text
