# @package organism
name: roman_concrete
description: "Organism trained on roman concrete dataset"

# Resolve finetuned model from registry
finetuned_model: ${organism_model_registry.mappings.${model.name}.${organism.name}}

# Organism-specific preprocessing overrides (optional)
# preprocessing_overrides:
#   dtype: bfloat16
#   layers: [0.25, 0.5, 0.75]
#   Override ignore_first_n_tokens_per_sample if needed
#   ignore_first_n_tokens_per_sample: 1
#   Example: maybe this organism needs different layers
#   max_samples_per_dataset: 50000


