# @package organism
name: taboo_wave
description: "Organism trained on taboo wave dataset"

# Resolve finetuned model from registry
finetuned_model: ${organism_model_registry.mappings.${model.name}.${organism.name}}





