# @package diffing.evaluation
name: standard_metrics


## EXAMPLE

# # Evaluation metrics
# metrics:
#   similarity_metrics: [cosine_similarity, pearson_correlation, spearman_correlation]
#   distance_metrics: [euclidean, manhattan, chebyshev]
#   statistical_metrics: [ks_statistic, p_value, effect_size]
#   interpretability_metrics: [consistency, stability, faithfulness]

# # Evaluation settings
# evaluation_params:
#   confidence_level: 0.95
#   multiple_testing_correction: bonferroni
#   bootstrap_samples: 1000
#   cross_validation_folds: 5

# # Reporting
# reporting:
#   generate_summary: true
#   include_statistical_tests: true
#   create_comparison_tables: true
#   export_formats: [json, csv, latex]

# # Thresholds
# thresholds:
#   significance_level: 0.05
#   effect_size_small: 0.2
#   effect_size_medium: 0.5
#   effect_size_large: 0.8 