# @package model
name: gemma3_1B
model_id: google/gemma-3-1b-it
end_of_turn_token: <end_of_turn>
attn_implementation: eager
ignore_first_n_tokens_per_sample: 0
token_level_replacement: null
dtype: float32