# @package finetune.task
name: question_answering
type: qa

# Dataset configuration
dataset:
  name: squad_v2
  train_split: train
  val_split: validation
  test_split: validation
  context_column: context
  question_column: question
  answer_column: answers
  max_length: 384
  doc_stride: 128

# Task-specific parameters
task_params:
  loss_function: qa_loss
  metrics: [exact_match, f1]
  max_answer_length: 30
  n_best_size: 20

# Data preprocessing
preprocessing:
  lowercase: false
  handle_impossible: true
  truncation: true
  padding: max_length 